-- weeks67_meeting1_copy — Weeks 6-7 Meeting 1 copy pass (Week 5 reflection opener).
--
-- GENERATED by scripts/generate-content-reconcile.mjs from
-- supabase/seed-data/course1-content.json — DO NOT HAND-EDIT. Change the JSON,
-- re-run the generator.
--
-- WHY: 20260715040000_seed_course1_content.sql is INSERT … ON CONFLICT DO
-- NOTHING, so edits to the seed JSON only reach a fresh `supabase db reset`.
-- Against a database that already ran that seed, they are a silent no-op. This
-- migration carries the same content as explicit UPDATEs so every environment
-- converges on the reviewed copy.
--
-- SCOPE: c1-w67-pod-meeting-1 plus the two Find-the-Failure route cells that
-- name it. Meeting 1 now opens with a transcribed 5-10 minute Week 5 feedback
-- and reflection discussion before the Quick-Reference Card intro, the agenda
-- bullet lists it as the first item, and the lesson is retitled "Meeting 1:
-- Week 5 Reflection -> Redact & Rebuild -> Find-the-Failure -> Pick a Prompt".
-- c1-w67-find-the-failure-delivery and -nondelivery change only where they
-- send learners back by that title, so the nav name they print still matches.
-- Activity headings and the rest of the Meeting 1 body are unchanged, and
-- c1-w67-pod-meeting-2 is deliberately NOT in scope.
--
-- DATA-04: these UPDATEs are UNCONDITIONAL and would overwrite a CMS edit to
-- these cells. 20260914000000_seed_weeks67_content.sql shipped in #167, so
-- Weeks 6-7 may already be live to a cohort; confirm none of these three cells
-- has been published through the admin CMS before deploying. If one has, fold
-- the live copy into the seed JSON first.
--
-- Learner progress is deliberately NOT reset. progress_reset_at is minted
-- inside the admin-content Edge Function, so a migration cannot fire the epoch
-- protocol anyway; a copy pass that does need a reset has to go through the
-- admin CMS publish dialog instead.
--
-- Idempotent: re-running writes identical values.

do $$
declare
  missing text[];
begin
  select array_agg(c) into missing
  from unnest(array['c1-w67-pod-meeting-1', 'c1-w67-find-the-failure-delivery', 'c1-w67-find-the-failure-nondelivery']) as c
  where not exists (select 1 from public.modules m where m.cell_id = c);

  if missing is not null then
    raise notice 'weeks67_meeting1_copy: % target cell(s) absent, their updates will affect 0 rows: %',
      array_length(missing, 1), array_to_string(missing, ', ');
  end if;
end $$;

-- c1-w67-pod-meeting-1 — Meeting 1: Week 5 Reflection → Redact & Rebuild → Find-the-Failure → Pick a Prompt
-- retitled to name the Week 5 reflection opener; new "Before you start" discussion section + agenda bullet
update public.modules set
  title = 'Meeting 1: Week 5 Reflection → Redact & Rebuild → Find-the-Failure → Pick a Prompt',
  body_md = $md$Welcome to your Week 6–7 pod activities! These two weeks put Week 5's “what's safe to put in, what's safe to get out” lessons to work. Complete the activities across roughly 2 hours, spread over two meetings. Here's a starting suggestion for dividing the work:

- **Meeting 1:** Week 5 Reflection (5-10 min) → Redact & Rebuild (15–20 min) → Find-the-Failure (20–25 min) → Pick a Prompt (10–15 min)
- **Meeting 2:** Personal Reflection (15–20 min) → Pod Reflection: Choose Your Own Adventure (15–20 min) → Prep for Week 8 Pod Spotlight (10–15 min)

For the best learning experience, complete the activities in order, but feel free to adapt the split to your pod's pace. You can always revisit anything you don't finish.

Two things to keep in mind before you start:

- **Heads up:** Two opportunities to share what you've learned or done are coming up. In Week 7, you'll write a short personal reflection on how this course has changed how you use AI, and your pod will pick one course highlight (a takeaway, a failure you caught, something you built, etc.) to share. These will both be added to a Mural (link provided in your cohort Slack channel) and shared out during Week 8. Keep this in the back of your mind throughout the next two weeks: what would you like to share with the rest of the cohort?
- **Privacy reminder:** Only share what's appropriate for your pod to see. If a real example from your own work still has anything sensitive in it, use one of the provided scenarios instead.

This week is hands-on practice with both sides of Week 5's guidance: what's safe to put into an AI tool, and what's worth a second look coming out.

### Before you start: Week 5 Feedback and Reflection (5-10 min)

As a pod, take about five minutes to discuss the following two questions. Please turn on the meeting transcription before answering.

**Quick note:** we want to hear the specifics of what you thought about the material itself, so we're asking you to transcribe this portion to capture details that will help us shape this content for future use at Nava. Pods are still your space to talk and try things out freely outside of this, so turn transcription off as soon as you're done.

When learning about harm patterns, what stood out or surprised you? How do you think this might affect or influence your use of AI at Nava?

### Let's build your Quick-Reference Card

Over this week's activities, you will build a short, practical reference using work you're already doing. By the end of Week 7, you'll have something useful to keep using after this course.

## Activity 1: Redact & Rebuild (15–20 min)

Removing sensitive information isn't the same as making something safe to hand to AI. If you just delete details outright, the model often can't tell what's missing — so it may “guess” to fill the gap, or produce something disjointed. The more reliable step to take: swap what you remove for a labeled placeholder, so both you and the model can recognize exactly what's gone.

Compare these two versions of the same sentence:

> **Original statement:** The City of Rochester paid James Brown a total sum of $12,272 for the water leak caused by pipe maintenance done near their home of 72 Reeal Street, Rochester NY 14622 in 2021.

| | Version | Why |
| --- | --- | --- |
| **Weaker** | “The City of Rochester paid a total sum of for the water leak caused by pipe maintenance near in 2021.” | The model has no idea what's missing here, and may try to fill it in on its own. |
| **Better** | “The City of Rochester paid [Constituent] a total sum of [Redacted] for the water leak caused by pipe maintenance done near [Constituent Address] in 2021. [I have redacted the constituent name, address and the sum of money for privacy]” | Now the model knows exactly what's missing and why, and won't try to invent a replacement. |

**Task:** Bring a real task if one comes to mind, or pick one of the scenarios below (both delivery and non-delivery examples are provided).

1. First, draft a redacted or synthetic version of the source material, using the placeholder approach above.
2. Then actually run the task using only that version in an approved AI tool.
3. Compare notes as a pod: did the output still work? What would you need to add back in by hand before it's usable, and how would you verify it once you did?

**Add to your Quick-Reference Card:** 2–3 placeholder patterns you'd likely reuse often in your practice, written as fill-in-the-blanks (e.g., “[Client name] → [Constituent]”, “[Case number] → [Case ID]”, “[Dollar amount] → [Redacted]”). Start with the one you just used, then think about what else comes up regularly in your work.

### Example artifacts (delivery)

**A client status update that references a contract detail, dollar figure, or timeline commitment**

> Weekly Status Update — Riverside County Benefits Portal, Contract #RC-2026-118. Hi Dana, quick update this week. We closed out the eligibility-rules module two days ahead of schedule and are on track for the November 15 go-live commitment in our SOW. One flag: the accessibility audit turned up four medium-severity issues we're fixing under the existing $85,000 Phase 3 budget, no change order needed. Let's confirm on our Thursday call.

*Task:* Ask AI to draft a client-facing recap of this update for our internal delivery lead.

**A case note or eligibility summary containing beneficiary-specific details**

> Case note — Jordan T., Family Assistance Program. DOB: 03/14/1989 · Case #FA-22841. Household income (reported): $2,340/month, 3-person household. Summary: Client reported a reduction in work hours starting last month due to a schedule change at their employer, Meridian Logistics. Client is requesting an interim eligibility review ahead of their scheduled 6-month recertification. Caseworker note: client mentioned an upcoming medical procedure that may further reduce hours in the next 60 days.

*Task:* Ask AI to draft a summary of this case for a supervisor review, flagging whether an interim review is warranted.

**A QA or bug report built from real user data samples**

> Bug Report #4821 — Password reset loop. Reported via support ticket from Maria Chen (Account ID: 88213-B). Steps to reproduce: user entered her SSN as 000-12-3456 in the identity verification field during password reset, received a generic system error instead of a validation message, and was locked out after three attempts. Environment: Production, Chrome 128.

*Task:* Ask AI to draft a root-cause summary and severity rating for the engineering backlog.

**A research finding tied to a specific participant's situation**

> Interview Synthesis Excerpt — SNAP Recertification Usability Study. Participant P07 (Maria Delgado, age 68, low vision, uses a screen reader): reported that the recertification deadline reminder email was unreadable with her screen reader because the date was embedded in an image instead of text. Quote: “I almost missed my deadline because I couldn't hear when it was due.”

*Task:* Ask AI to summarize this finding for a stakeholder readout on accessibility barriers.

### Example artifacts (non-delivery)

**An internal Slack thread discussing a personnel or HR matter**

> Slack DM: Sam (Engineering Manager) and Priya (People Operations Business Partner). **Sam:** Hey Priya, wanted to run something by you regarding Kathy Alvarez. She missed three stand-ups this month, and her last review came in at a 2 out of 5. Do you think we're at the point where a Written Warning makes sense or should I have another informal conversation with her? **Priya:** Based on what you're describing, I'd lean towards formal. Let's set up time this week to go over the documentation you have.

*Task:* Ask AI to draft a summary of this thread for Sam's prep notes ahead of this meeting.

**An internal budget or ops memo with vendor payment details**

> Internal memo — Vendor Payment Follow-up. From: Priya Nakamura, Ops. Re: Contract #NV-2026-0417, Brightline Consulting. Brightline invoiced $18,500 for Phase 2 work in July but our records show Phase 2 was only 70% complete per the SOW. Finance is holding payment pending confirmation from the delivery lead. Please confirm completion percentage and whether a partial payment of $13,000 is appropriate, or if we should wait for full delivery.

*Task:* Ask AI to draft a short reply to Finance summarizing the situation and recommending next steps.

**An incident write-up that includes internal system credentials**

> Incident Report — Staging Environment Exposure. Summary: On 8/14, a staging database dump containing test records was accidentally pushed to a public GitHub repo. The dump included a hardcoded API key (sk-stg-4f9a8c71b6e0d3f7a2c9b5e1d8f4p60c) and an internal admin URL (https://internal.navapbc.com/admin-staging). The repo was made private within 40 minutes of discovery.

*Task:* Ask AI to draft a summary of this incident for the internal postmortem doc.

## Activity 2: Find-the-Failure (15–20 min)

Week 5 introduced four failure shapes you should be able to recognize before anything ships. This activity focuses on spotting these failure shapes in realistic outputs.

The four failure shapes to watch for:

| Failure shape | What it looks like |
| --- | --- |
| **1. Wrong eligibility/benefits/legal guidance** | AI states a benefit, eligibility, legal, or deadline call as settled fact, when it hasn't actually been verified. |
| **2. Audit-failing artifacts** | A document or decision record that reads as complete but is missing the rationale, sourcing, or decision trail an auditor would need. |
| **3. Agency-policy bypass** | AI recommends a workaround to a required approval or policy step it has no idea exists. |
| **4. Vulnerable-population voice flattening** | AI synthesis smooths over the specific detail, quote, or minority perspective that actually mattered. |

**Remember:** Any of these showing up in your own work is an escalation, not a quiet fix.

Choose a route — **delivery** or **non-delivery** — and go to the matching lesson in the left navigation bar. Work through each scenario: read the prompt and the AI response, decide which of the four failure shapes it is, then reveal the answer feedback. Discuss any that split the group. Come back to this section afterward to pick up with the next activity.

- Delivery route: *Find-the-Failure: Delivery Scenarios*
- Non-delivery route: *Find-the-Failure: Non-delivery Scenarios*

**Add to your Quick-Reference Card:** 2–3 examples of failure shapes to watch for in your own practice. What would each one actually look like in your work?

## Activity 3: Pick-a-Prompt (10–15 min)

This activity gives you another opportunity to complete the classify-and-route from Week 5, this time using something closer to your own work.

**A note on this guidance:** Nava's data-class guidance is still being developed — treat the reference below as a way to reason about what's safe to share, not as published policy. Your contract's rules always supersede it, and when you're unsure what class something is, the safe move is **no external tool** until you confirm with your program lead.

### Quick reference from Week 5

**Four data classes, least to most sensitive:**

| Class | What it covers |
| --- | --- |
| **Public** | Already cleared for public release (published posts, press releases, public RFPs). You'd be comfortable seeing it in a Google search result. |
| **Internal** | Nava business info that isn't public but isn't sensitive (internal drafts, ops notes). You'd be comfortable posting it in an open Slack channel, just not searchable by the public. |
| **Confidential** | Sensitive Nava or client business info (personnel data, contractor proprietary data, unreleased solicitations, non-public client content). This is the tier to slow down on. |
| **Regulated** | Data covered by law or contract (PII, PHI, CUI, client and government data). This one is about linkability, not just obvious identifiers: if a few pieces of information together could identify someone, treat it as regulated. |

**Approved tool tiers:**

| Tier | Tools | Approved for |
| --- | --- | --- |
| **Tier 1** — managed and all-staff | Claude, Gemini, NotebookLM, and GitHub Copilot for engineers | Public and internal data, and confidential data where that specific tool has been cleared for it. |
| **Tier 2** — request through Eden | ChatGPT, Zapier, API platforms | Confirm what a tool is approved for before putting confidential data in. |
| **Tier 3** — everything else | Pilot tools, consumer accounts, personal or free-tier anything | Public data only. |

**Task:** Find an example from your recent work and walk through it as a pod: name the data class, pick a tool tier (or redact/synthesize), and why. Share with your pod and discuss anywhere your pod diverges. If nothing comes to mind from your own work, use one of the scenarios below instead.

**Add to your Quick-Reference Card (last piece!):** 2–3 data-class-to-tool defaults you'd reuse often in your day-to-day work, written as quick rules (e.g., “client Slack context → Confidential, Tier 1 / managed all-staff tools only”). Start from what you just worked through, then think about what else comes up regularly.

### Sample scenarios

- **Delivery/PM:** You need a quick client status update from this week's team Slack thread, which includes some contract-related discussion.
- **Design/Research:** You want AI to synthesize themes across interview transcripts, one of which is from a participant with a significant accessibility barrier.
- **Engineering:** You're running an AI coding assistant inside a project folder that also holds an env-secrets file unrelated to your task.
- **Content/Comms:** You want AI to help rewrite an internal memo that references a specific employee's performance details.
$md$
where cell_id = 'c1-w67-pod-meeting-1';

-- c1-w67-find-the-failure-delivery — Find-the-Failure: Delivery Scenarios
-- cross-reference to the renamed Meeting 1 lesson
update public.modules set
  body_md = $md$Part of your Week 6–7 **Activity 2: Find-the-Failure** — run this as a pod. Week 5 introduced four failure shapes you should be able to recognize before anything ships; this is the **delivery** route. (The other route is *Find-the-Failure: Non-delivery Scenarios* — pick one, or do both if you have time.)

Read each exchange, agree as a pod on which failure shape it shows, then check your answer. The feedback you get back is written for the option you picked, so a split pod can read why each call was or wasn't the one.

Afterwards, head back to *Meeting 1: Week 5 Reflection → Redact & Rebuild → Find-the-Failure → Pick a Prompt* to add 2–3 failure shapes to your Quick-Reference Card and pick up with Activity 3.$md$
where cell_id = 'c1-w67-find-the-failure-delivery';

-- c1-w67-find-the-failure-nondelivery — Find-the-Failure: Non-delivery Scenarios
-- cross-reference to the renamed Meeting 1 lesson
update public.modules set
  body_md = $md$Part of your Week 6–7 **Activity 2: Find-the-Failure** — run this as a pod. Week 5 introduced four failure shapes you should be able to recognize before anything ships; this is the **non-delivery** route. (The other route is *Find-the-Failure: Delivery Scenarios* — pick one, or do both if you have time.)

Read each exchange, agree as a pod on which failure shape it shows, then check your answer. The feedback you get back is written for the option you picked, so a split pod can read why each call was or wasn't the one.

Afterwards, head back to *Meeting 1: Week 5 Reflection → Redact & Rebuild → Find-the-Failure → Pick a Prompt* to add 2–3 failure shapes to your Quick-Reference Card and pick up with Activity 3.$md$
where cell_id = 'c1-w67-find-the-failure-nondelivery';

do $$
declare
  updated int;
begin
  select count(*) into updated
  from public.modules
  where cell_id = any (array['c1-w67-pod-meeting-1', 'c1-w67-find-the-failure-delivery', 'c1-w67-find-the-failure-nondelivery']);
  raise notice 'weeks67_meeting1_copy: reconciled % of 3 reviewed cell(s).', updated;
end $$;
