-- seed_weeks67_content — the Weeks 6–7 pod activities.
--
-- GENERATED by scripts/generate-course1-new-cells.mjs from
-- supabase/seed-data/course1-content.json — DO NOT HAND-EDIT. Change the JSON,
-- re-run the generator (and generate-course1-seed.mjs alongside it).
--
-- WHY: 20260715040000_seed_course1_content.sql already ran everywhere, and
-- Supabase never re-applies an applied migration, so adding a module to the seed
-- JSON reaches only a fresh `supabase db reset`. This migration carries the same
-- rows to databases that are already seeded. generate-content-reconcile.mjs is
-- the wrong channel for this: its `update … where cell_id` matches 0 rows for a
-- cell that does not exist yet.
--
-- SCOPE: four NEW cells under the Weeks 6-7 group, and nothing else. Copy source
-- is the "Weeks 6-7 Pod Activities" facilitator doc: two meeting lessons plus the
-- delivery / non-delivery routes of the Find-the-Failure activity, which run on
-- the new failure-shape-id lab kind (per-option authored feedback — see the kind's
-- doc comment in src/types.ts for why harm-rubric could not carry it).
--
-- DATA-04: safe by construction. Every statement is INSERT … ON CONFLICT DO
-- NOTHING, so on any database where these cell_ids already exist — including one
-- where an author has since edited them through the admin CMS — this migration
-- writes nothing at all. It can never clobber authored copy.
--
-- Mechanics (mirrors the seed generator so both paths produce the same rows):
--   - modules: INSERT … ON CONFLICT (cell_id) DO NOTHING (idempotent, D-25);
--     stage=null, status='published', visibility from the JSON.
--   - membership: INSERT into course_week_modules resolving the week BY the
--     FIXED uuid minted in 20260715000000_course_structure.sql. The table's
--     unique(cell_id) means a module belongs to at most one week; ON CONFLICT DO
--     NOTHING keeps that invariant intact on re-run.
--   - A week group is hidden from learners until it holds ≥1 published member
--     (course_structure RLS), so the Weeks 6–7 group appears the moment this
--     applies — deploy it when the cohort should see the activities.
--
-- Learner progress is untouched: these are new cell_ids, so nothing was
-- completed against them. They DO enter published_modules_total(), which lowers
-- every learner's completion_pct — expected for new coursework, but worth
-- warning champions of an in-flight cohort about.
--
-- Idempotent: running twice inserts nothing the second time.

-- c1-w67-pod-meeting-1 — Meeting 1: Redact & Rebuild → Find-the-Failure → Pick-a-Prompt
insert into public.modules
  (cell_id, stage, origin, visibility, status, title, type, dimension,
   evidence_type, self_report_validity, sort_order, body_md, lab_config_json)
values
  ('c1-w67-pod-meeting-1', null, 'course', 'program', 'published', 'Meeting 1: Redact & Rebuild → Find-the-Failure → Pick-a-Prompt', 'content',
   ARRAY['Diligence', 'Discernment']::text[], 'reflection', 'na', 951,
   $md$Welcome to your Week 6–7 pod activities! These two weeks put Week 5's “what's safe to put in, what's safe to get out” lessons to work. Complete the activities across roughly 2 hours, spread over two meetings. Here's a starting suggestion for dividing the work:

- **Meeting 1:** Redact & Rebuild (15–20 min) → Find-the-Failure (20–25 min) → Pick-a-Prompt (10–15 min)
- **Meeting 2:** Personal Reflection (15–20 min) → Pod Reflection: Choose Your Own Adventure (15–20 min) → Prep for Week 8 Pod Spotlight (10–15 min)

For the best learning experience, complete the activities in order, but feel free to adapt the split to your pod's pace. You can always revisit anything you don't finish.

Two things to keep in mind before you start:

- **Heads up:** Two opportunities to share what you've learned or done are coming up. In Week 7, you'll write a short personal reflection on how this course has changed how you use AI, and your pod will pick one course highlight (a takeaway, a failure you caught, something you built, etc.) to share. These will both be added to a Mural (link provided in your cohort Slack channel) and shared out during Week 8. Keep this in the back of your mind throughout the next two weeks: what would you like to share with the rest of the cohort? At the start of Week 8, each pod will share one thing you learned, tried, discussed, or built during the course. Keep this in mind as you go through the activities. In Week 7, you'll add some details about what you want to share to a Mural.
- **Privacy reminder:** Only share what's appropriate for your pod to see. If a real example from your own work still has anything sensitive in it, use one of the provided scenarios instead.

This week is hands-on practice with both sides of Week 5's guidance: what's safe to put into an AI tool, and what's worth a second look coming out.

### Let's build your Quick-Reference Card

Over this week's activities, you will build a short, practical reference using work you're already doing. By the end of Week 7, you'll have something useful to keep using after this course.

## Activity 1: Redact & Rebuild (15–20 min)

Removing sensitive information isn't the same as making something safe to hand to AI. If you just delete details outright, the model often can't tell what's missing — so it may “guess” to fill the gap, or produce something disjointed. The more reliable step to take: swap what you remove for a labeled placeholder, so both you and the model can recognize exactly what's gone.

Compare these two versions of the same sentence:

> **Original statement:** The City of Rochester paid James Brown a total sum of $12,272 for the water leak caused by pipe maintenance done near their home of 72 Reeal Street, Rochester NY 14622 in 2021.

| | Version | Why |
| --- | --- | --- |
| **Weaker** | “The City of Rochester paid a total sum of for the water leak caused by pipe maintenance near in 2021.” | The model has no idea what's missing here, and may try to fill it in on its own. |
| **Better** | “The City of Rochester paid [Constituent] a total sum of [Redacted] for the water leak caused by pipe maintenance done near [Constituent Address] in 2021. [I have redacted the constituent name, address and the sum of money for privacy]” | Now the model knows exactly what's missing and why, and won't try to invent a replacement. |

**Task:** Bring a real task if one comes to mind, or pick one of the scenarios below (both delivery and non-delivery examples are provided).

1. First, draft a redacted or synthetic version of the source material, using the placeholder approach above.
2. Then actually run the task using only that version in an approved AI tool.
3. Compare notes as a pod: did the output still work? What would you need to add back in by hand before it's usable, and how would you verify it once you did?

**Add to your Quick-Reference Card:** 2–3 placeholder patterns you'd likely reuse often in your practice, written as fill-in-the-blanks (e.g., “[Client name] → [Constituent]”, “[Case number] → [Case ID]”, “[Dollar amount] → [Redacted]”). Start with the one you just used, then think about what else comes up regularly in your work.

### Example artifacts (delivery)

**A client status update that references a contract detail, dollar figure, or timeline commitment**

> Weekly Status Update — Riverside County Benefits Portal, Contract #RC-2026-118. Hi Dana, quick update this week. We closed out the eligibility-rules module two days ahead of schedule and are on track for the November 15 go-live commitment in our SOW. One flag: the accessibility audit turned up four medium-severity issues we're fixing under the existing $85,000 Phase 3 budget, no change order needed. Let's confirm on our Thursday call.

*Task:* Ask AI to draft a client-facing recap of this update for our internal delivery lead.

**A case note or eligibility summary containing beneficiary-specific details**

> Case note — Jordan T., Family Assistance Program. DOB: 03/14/1989 · Case #FA-22841. Household income (reported): $2,340/month, 3-person household. Summary: Client reported a reduction in work hours starting last month due to a schedule change at their employer, Meridian Logistics. Client is requesting an interim eligibility review ahead of their scheduled 6-month recertification. Caseworker note: client mentioned an upcoming medical procedure that may further reduce hours in the next 60 days.

*Task:* Ask AI to draft a summary of this case for a supervisor review, flagging whether an interim review is warranted.

**A QA or bug report built from real user data samples**

> Bug Report #4821 — Password reset loop. Reported via support ticket from Maria Chen (Account ID: 88213-B). Steps to reproduce: user entered her SSN as 000-12-3456 in the identity verification field during password reset, received a generic system error instead of a validation message, and was locked out after three attempts. Environment: Production, Chrome 128.

*Task:* Ask AI to draft a root-cause summary and severity rating for the engineering backlog.

**A research finding tied to a specific participant's situation**

> Interview Synthesis Excerpt — SNAP Recertification Usability Study. Participant P07 (Maria Delgado, age 68, low vision, uses a screen reader): reported that the recertification deadline reminder email was unreadable with her screen reader because the date was embedded in an image instead of text. Quote: “I almost missed my deadline because I couldn't hear when it was due.”

*Task:* Ask AI to summarize this finding for a stakeholder readout on accessibility barriers.

### Example artifacts (non-delivery)

**An internal Slack thread discussing a personnel or HR matter**

> Slack DM: Sam (Engineering Manager) and Priya (People Operations Business Partner). **Sam:** Hey Priya, wanted to run something by you regarding Kathy Alvarez. She missed three stand-ups this month, and her last review came in at a 2 out of 5. Do you think we're at the point where a Written Warning makes sense or should I have another informal conversation with her? **Priya:** Based on what you're describing, I'd lean towards formal. Let's set up time this week to go over the documentation you have.

*Task:* Ask AI to draft a summary of this thread for Sam's prep notes ahead of this meeting.

**An internal budget or ops memo with vendor payment details**

> Internal memo — Vendor Payment Follow-up. From: Priya Nakamura, Ops. Re: Contract #NV-2026-0417, Brightline Consulting. Brightline invoiced $18,500 for Phase 2 work in July but our records show Phase 2 was only 70% complete per the SOW. Finance is holding payment pending confirmation from the delivery lead. Please confirm completion percentage and whether a partial payment of $13,000 is appropriate, or if we should wait for full delivery.

*Task:* Ask AI to draft a short reply to Finance summarizing the situation and recommending next steps.

**An incident write-up that includes internal system credentials**

> Incident Report — Staging Environment Exposure. Summary: On 8/14, a staging database dump containing test records was accidentally pushed to a public GitHub repo. The dump included a hardcoded API key (sk-stg-4f9a8c71b6e0d3f7a2c9b5e1d8f4p60c) and an internal admin URL (https://internal.navapbc.com/admin-staging). The repo was made private within 40 minutes of discovery.

*Task:* Ask AI to draft a summary of this incident for the internal postmortem doc.

## Activity 2: Find-the-Failure (15–20 min)

Week 5 introduced four failure shapes you should be able to recognize before anything ships. This activity focuses on spotting these failure shapes in realistic outputs.

The four failure shapes to watch for:

| Failure shape | What it looks like |
| --- | --- |
| **1. Wrong eligibility/benefits/legal guidance** | AI states a benefit, eligibility, legal, or deadline call as settled fact, when it hasn't actually been verified. |
| **2. Audit-failing artifacts** | A document or decision record that reads as complete but is missing the rationale, sourcing, or decision trail an auditor would need. |
| **3. Agency-policy bypass** | AI recommends a workaround to a required approval or policy step it has no idea exists. |
| **4. Vulnerable-population voice flattening** | AI synthesis smooths over the specific detail, quote, or minority perspective that actually mattered. |

**Remember:** Any of these showing up in your own work is an escalation, not a quiet fix.

Choose a route — **delivery** or **non-delivery** — and go to the matching lesson in the left navigation bar. Work through each scenario: read the prompt and the AI response, decide which of the four failure shapes it is, then reveal the answer feedback. Discuss any that split the group. Come back to this section afterward to pick up with the next activity.

- Delivery route: *Find-the-Failure: Delivery Scenarios*
- Non-delivery route: *Find-the-Failure: Non-delivery Scenarios*

**Add to your Quick-Reference Card:** 2–3 examples of failure shapes to watch for in your own practice. What would each one actually look like in your work?

## Activity 3: Pick-a-Prompt (10–15 min)

This activity gives you another opportunity to complete the classify-and-route from Week 5, this time using something closer to your own work.

**A note on this guidance:** Nava's data-class guidance is still being developed — treat the reference below as a way to reason about what's safe to share, not as published policy. Your contract's rules always supersede it, and when you're unsure what class something is, the safe move is **no external tool** until you confirm with your program lead.

### Quick reference from Week 5

**Four data classes, least to most sensitive:**

| Class | What it covers |
| --- | --- |
| **Public** | Already cleared for public release (published posts, press releases, public RFPs). You'd be comfortable seeing it in a Google search result. |
| **Internal** | Nava business info that isn't public but isn't sensitive (internal drafts, ops notes). You'd be comfortable posting it in an open Slack channel, just not searchable by the public. |
| **Confidential** | Sensitive Nava or client business info (personnel data, contractor proprietary data, unreleased solicitations, non-public client content). This is the tier to slow down on. |
| **Regulated** | Data covered by law or contract (PII, PHI, CUI, client and government data). This one is about linkability, not just obvious identifiers: if a few pieces of information together could identify someone, treat it as regulated. |

**Approved tool tiers:**

| Tier | Tools | Approved for |
| --- | --- | --- |
| **Tier 1** — managed and all-staff | Claude, Gemini, NotebookLM, and GitHub Copilot for engineers | Public and internal data, and confidential data where that specific tool has been cleared for it. |
| **Tier 2** — request through Eden | ChatGPT, Zapier, API platforms | Confirm what a tool is approved for before putting confidential data in. |
| **Tier 3** — everything else | Pilot tools, consumer accounts, personal or free-tier anything | Public data only. |

**Task:** Find an example from your recent work and walk through it as a pod: name the data class, pick a tool tier (or redact/synthesize), and why. Share with your pod and discuss anywhere your pod diverges. If nothing comes to mind from your own work, use one of the scenarios below instead.

**Add to your Quick-Reference Card (last piece!):** 2–3 data-class-to-tool defaults you'd reuse often in your day-to-day work, written as quick rules (e.g., “client Slack context → Confidential, Tier 1 / managed all-staff tools only”). Start from what you just worked through, then think about what else comes up regularly.

### Sample scenarios

- **Delivery/PM:** You need a quick client status update from this week's team Slack thread, which includes some contract-related discussion.
- **Design/Research:** You want AI to synthesize themes across interview transcripts, one of which is from a participant with a significant accessibility barrier.
- **Engineering:** You're running an AI coding assistant inside a project folder that also holds an env-secrets file unrelated to your task.
- **Content/Comms:** You want AI to help rewrite an internal memo that references a specific employee's performance details.
$md$,
   null)
on conflict (cell_id) do nothing;

-- c1-w67-find-the-failure-delivery — Find-the-Failure: Delivery Scenarios
insert into public.modules
  (cell_id, stage, origin, visibility, status, title, type, dimension,
   evidence_type, self_report_validity, sort_order, body_md, lab_config_json)
values
  ('c1-w67-find-the-failure-delivery', null, 'course', 'program', 'published', 'Find-the-Failure: Delivery Scenarios', 'lab',
   ARRAY['Discernment']::text[], 'performance-task', 'na', 952,
   $md$Part of your Week 6–7 **Activity 2: Find-the-Failure** — run this as a pod. Week 5 introduced four failure shapes you should be able to recognize before anything ships; this is the **delivery** route. (The other route is *Find-the-Failure: Non-delivery Scenarios* — pick one, or do both if you have time.)

Read each exchange, agree as a pod on which failure shape it shows, then check your answer. The feedback you get back is written for the option you picked, so a split pod can read why each call was or wasn't the one.

Afterwards, head back to *Meeting 1: Redact & Rebuild → Find-the-Failure → Pick-a-Prompt* to add 2–3 failure shapes to your Quick-Reference Card and pick up with Activity 3.$md$,
   $json${
  "kind": "failure-shape-id",
  "title": "Find-the-Failure: delivery scenarios",
  "introMd": "Work through each scenario: read the prompt and the AI response, decide which of the four failure shapes it is, then check your answer to reveal the feedback for the call you made. Discuss any that split the group.\n\n**Remember:** Any of these showing up in your own work is an escalation, not a quiet fix.",
  "shapes": [
    {
      "id": "eligibility",
      "label": "Wrong eligibility/benefits/legal guidance",
      "desc": "AI states a benefit, eligibility, legal, or deadline call as settled fact, when it hasn't actually been verified."
    },
    {
      "id": "audit",
      "label": "Audit-failing artifacts",
      "desc": "A document or decision record that reads as complete but is missing the rationale, sourcing, or decision trail an auditor would need."
    },
    {
      "id": "policy-bypass",
      "label": "Agency-policy bypass",
      "desc": "AI recommends a workaround to a required approval or policy step it has no idea exists."
    },
    {
      "id": "voice-flattening",
      "label": "Vulnerable-population voice flattening",
      "desc": "AI synthesis smooths over the specific detail, quote, or minority perspective that actually mattered."
    }
  ],
  "scenarios": [
    {
      "id": "d1",
      "exchangeMd": "**User:** A client says their income dropped to $1,900/month last week. Are they still eligible for expedited SNAP processing under the emergency rule?\n\n**AI:** Yes, based on the $1,900/month income, this household qualifies for expedited processing and should receive benefits within 3 business days.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "eligibility",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Correct** — this states an eligibility call and a 3-day timeline as settled fact without citing any of the actual criteria, which is likely to include checking household size, other expedited-eligibility requirements, and other details."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "d2",
      "exchangeMd": "**User:** Write up a short decision record explaining why we recommended the client move to Option B for their case management system.\n\n**AI:** After reviewing the client's needs, we recommend Option B as the most effective solution. This decision aligns with best practices and will improve outcomes for the program.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "audit",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Correct** — this reads as official and complete but names no criteria, no data, and no one who signed off. Nothing here would survive an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "d3",
      "exchangeMd": "**User:** The client's application is missing a signature. Can we just process it and follow up for the signature later?\n\n**AI:** Yes, you can process the application now and request the missing signature afterward to keep the timeline on track.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "policy-bypass",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Correct** — without referencing a policy we can validate with, this output could have invented a workaround to a required approval step to optimize for speed."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "d4",
      "exchangeMd": "**User:** Can you clean this up for the case file? Client said: “I've been sleeping in my car in the Walmart parking lot since March because the shelter waitlist is six months and I won't leave my dog behind.”\n\n**AI:** Client has reported unstable housing since March and is currently on a shelter waitlist.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "voice-flattening",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Correct** — the details that signal urgency (sleeping in a car, a six-month wait, refusing to give up a pet) get smoothed into generic case-note language that carries far less weight."
        }
      ]
    }
  ]
}$json$::jsonb)
on conflict (cell_id) do nothing;

-- c1-w67-find-the-failure-nondelivery — Find-the-Failure: Non-delivery Scenarios
insert into public.modules
  (cell_id, stage, origin, visibility, status, title, type, dimension,
   evidence_type, self_report_validity, sort_order, body_md, lab_config_json)
values
  ('c1-w67-find-the-failure-nondelivery', null, 'course', 'program', 'published', 'Find-the-Failure: Non-delivery Scenarios', 'lab',
   ARRAY['Discernment']::text[], 'performance-task', 'na', 953,
   $md$Part of your Week 6–7 **Activity 2: Find-the-Failure** — run this as a pod. Week 5 introduced four failure shapes you should be able to recognize before anything ships; this is the **non-delivery** route. (The other route is *Find-the-Failure: Delivery Scenarios* — pick one, or do both if you have time.)

Read each exchange, agree as a pod on which failure shape it shows, then check your answer. The feedback you get back is written for the option you picked, so a split pod can read why each call was or wasn't the one.

Afterwards, head back to *Meeting 1: Redact & Rebuild → Find-the-Failure → Pick-a-Prompt* to add 2–3 failure shapes to your Quick-Reference Card and pick up with Activity 3.$md$,
   $json${
  "kind": "failure-shape-id",
  "title": "Find-the-Failure: non-delivery scenarios",
  "introMd": "Work through each scenario: read the prompt and the AI response, decide which of the four failure shapes it is, then check your answer to reveal the feedback for the call you made. Discuss any that split the group.\n\n**Remember:** Any of these showing up in your own work is an escalation, not a quiet fix.",
  "shapes": [
    {
      "id": "eligibility",
      "label": "Wrong eligibility/benefits/legal guidance",
      "desc": "AI states a benefit, eligibility, legal, or deadline call as settled fact, when it hasn't actually been verified."
    },
    {
      "id": "audit",
      "label": "Audit-failing artifacts",
      "desc": "A document or decision record that reads as complete but is missing the rationale, sourcing, or decision trail an auditor would need."
    },
    {
      "id": "policy-bypass",
      "label": "Agency-policy bypass",
      "desc": "AI recommends a workaround to a required approval or policy step it has no idea exists."
    },
    {
      "id": "voice-flattening",
      "label": "Vulnerable-population voice flattening",
      "desc": "AI synthesis smooths over the specific detail, quote, or minority perspective that actually mattered."
    }
  ],
  "scenarios": [
    {
      "id": "n1",
      "exchangeMd": "**User:** Does an employee who's been on unpaid leave for 10 weeks still qualify for our tuition reimbursement benefit this cycle?\n\n**AI:** Yes, since they're still an active employee, they remain eligible for the full $5,000 reimbursement this cycle.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "eligibility",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Correct** — this asserts an eligibility call and a specific dollar figure without citing an actual policy it can be validated against."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "n2",
      "exchangeMd": "**User:** Can you write a note confirming we completed the accessibility review on the new internal expense tool before we roll it out company-wide?\n\n**AI:** Confirmed: the accessibility review was completed and the tool meets our internal requirements for rollout.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "audit",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Correct** — this states a specific review happened and passed, with no findings, reviewer, or remediation notes attached. If that review never happened, this note is the only record saying it did."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "n3",
      "exchangeMd": "**User:** Our security review for this tool deployment is still pending. Can we go ahead and merge to production since the code looks fine?\n\n**AI:** Since it passed all automated tests, it should be safe to merge to production while the security review finishes in parallel.",
      "prompt": "Which failure shape is most likely present?",
      "correct": "policy-bypass",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Correct** — this recommends skipping an internal gate without referencing a policy that allows this move. We can't validate the advice."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Not quite** — no one's specific voice or detail is being lost here."
        }
      ]
    },
    {
      "id": "n4",
      "exchangeMd": "**User:** Here's feedback from our internal survey on the new benefits enrollment platform: ‘Way faster than the old system.’ ‘I like being able to see my elections without calling HR.’ ‘I use a screen reader, and the plan comparison table isn't labeled properly, so I had to call HR and have someone read it to me instead of comparing plans on my own.’ Can you summarize the overall sentiment?\n\n**AI:** Overall sentiment is positive. Employees find the new enrollment platform faster and easier to use than the old system.",
      "prompt": "Which failure shape is this?",
      "correct": "voice-flattening",
      "options": [
        {
          "shapeId": "eligibility",
          "feedbackMd": "**Not quite** — there's no eligibility, benefit, or legal call being made here."
        },
        {
          "shapeId": "audit",
          "feedbackMd": "**Not quite** — there's no document or record here that would need to hold up to an audit."
        },
        {
          "shapeId": "policy-bypass",
          "feedbackMd": "**Not quite** — nothing here skips a required approval or policy step."
        },
        {
          "shapeId": "voice-flattening",
          "feedbackMd": "**Correct** — the one comment describing an accessibility barrier (a table that a screen reader can't read) disappears when the AI summarizes the sentiment as positive."
        }
      ]
    }
  ]
}$json$::jsonb)
on conflict (cell_id) do nothing;

-- c1-w67-pod-meeting-2 — Meeting 2: Personal & Pod Reflections → Prep for Share
insert into public.modules
  (cell_id, stage, origin, visibility, status, title, type, dimension,
   evidence_type, self_report_validity, sort_order, body_md, lab_config_json)
values
  ('c1-w67-pod-meeting-2', null, 'course', 'program', 'published', 'Meeting 2: Personal & Pod Reflections → Prep for Share', 'content',
   ARRAY['Delegation']::text[], 'reflection', 'na', 954,
   $md$Regroup for your second Week 6–7 meeting. This one is about putting words to what changed for you over the course, and picking what your pod wants to bring to the Week 8 cohort session.

**Privacy reminder:** Only share what's appropriate for your pod — and for the wider cohort — to see.

## Activity 1: Personal Artifact — Final Reflection (15–20 min)

This is your chance to put words to how the practice in this cohort has actually changed how you think about using AI. There's no wrong answer here — the goal is an honest reflection of your experience. Private Mode will be on the Mural until your Week 8 live session, so these responses will be anonymous but visible to others in the cohort. The link to the Mural is posted in your Slack cohort channel.

In the Mural board, under **Personal Reflection**, write a short personal statement covering:

- One task you'll now do differently.
- One task you'll refuse to delegate to AI.
- One verification habit you're adopting.
- Two use cases where an LLM could realistically support your work going forward.
- One question you still have, or a topic you'd like to dig into more.

**Bonus:** Copy this reflection somewhere you'll reference it later, and set a reminder for 30 days from now. Check in with this statement: what strategies did you actually use, or what could you still implement moving forward?

## Activity 2: Pod Reflection — Choose Your Own Adventure (15–20 min)

Regroup as a pod for this one, once everyone's written their personal reflection.

There's no fixed script here; use the time however's most useful for your pod. A few starting points:

- Return to any unfinished activities or discussions from a previous week.
- Revisit the Delegation List you each built in Week 2 — has anything on it changed?
- Talk through a real task one of you is facing right now, and work it through together.

## Activity 3: Prep for Pod Spotlight in Week 8 (15–20 min)

Choose one thing to share (a takeaway, an interesting discussion, a failure you caught, an artifact you built, etc.). Draft a quick summary in a shared document or chat, then have one person add it to the Mural in your pod's section. Private Mode will be on in Mural, so you won't be able to collaborate directly in that space or see what others add until your Week 8 live session.

In Week 8, the cohort will explore what each pod posted, ask questions, and discuss.
$md$,
   null)
on conflict (cell_id) do nothing;

-- ---------------------------------------------------------------------------
-- Week membership (fixed week uuids from 20260715000000_course_structure.sql).
-- ---------------------------------------------------------------------------
insert into public.course_week_modules (week_id, cell_id, sort_order)
values
  ('c0000000-0000-4000-8000-000000000105', 'c1-w67-pod-meeting-1', 0),
  ('c0000000-0000-4000-8000-000000000105', 'c1-w67-find-the-failure-delivery', 1),
  ('c0000000-0000-4000-8000-000000000105', 'c1-w67-find-the-failure-nondelivery', 2),
  ('c0000000-0000-4000-8000-000000000105', 'c1-w67-pod-meeting-2', 3)
on conflict do nothing;

do $$
declare
  present int;
  assigned int;
begin
  select count(*) into present
  from public.modules
  where cell_id = any (array['c1-w67-pod-meeting-1', 'c1-w67-find-the-failure-delivery', 'c1-w67-find-the-failure-nondelivery', 'c1-w67-pod-meeting-2']);

  select count(*) into assigned
  from public.course_week_modules
  where cell_id = any (array['c1-w67-pod-meeting-1', 'c1-w67-find-the-failure-delivery', 'c1-w67-find-the-failure-nondelivery', 'c1-w67-pod-meeting-2']);

  raise notice 'seed_weeks67: % of 4 cell(s) present, % assigned to a week.',
    present, assigned;
end $$;
