-- weeks34_pod_activity_copy — Weeks 3–4 pod-activity copy pass.
--
-- GENERATED by scripts/generate-content-reconcile.mjs from
-- supabase/seed-data/course1-content.json — DO NOT HAND-EDIT. Change the JSON,
-- re-run the generator.
--
-- WHY: 20260715040000_seed_course1_content.sql is INSERT … ON CONFLICT DO
-- NOTHING, so edits to the seed JSON only reach a fresh `supabase db reset`.
-- Against a database that already ran that seed, they are a silent no-op. This
-- migration carries the same content as explicit UPDATEs so every environment
-- converges on the reviewed copy.
--
-- SCOPE: the three Weeks 3-4 cells the copy pass changed, and only the columns
-- that changed. c1-w34-pod-kickoff: Activity 2 now tells pods to pick one Walk
-- the Workflow tab in the left nav and come back afterward; Activity 3 is
-- re-cut into three timeboxed steps and now sorts tasks into the Week 2 tiers
-- (Full pass to AI / AI-assisted / Human Only), adds the client-or-manager gut
-- check, and adds a shared-goal step that sets up the Meeting 2 exploration.
-- The cell is also retitled "Meeting 1: Intros -> Walk the Workflow ->
-- Delegation List" so the nav names the meeting and its agenda, matching the
-- "Meeting 2: AI Practice Scavenger Hunt" cell.
-- c1-w34-walk-the-workflow-general: the vendor guide is described as accurate,
-- the Slack thread now says it carries employees' names and personal situations
-- (so the risky-source call has the facts behind it), plus two grammar fixes in
-- feedback copy.
-- c1-w34-scavenger-hunt: punctuation fixes, a Cowork prompt hint, support-doc
-- links on the connectors and model-comparison exercises, and a closing
-- apply-it-to-your-work paragraph. The opening sentences are unchanged.
-- c1-w34-walk-the-workflow-delivery is deliberately NOT in scope — the review
-- left it unchanged.
--
-- DATA-04: these UPDATEs are UNCONDITIONAL and would overwrite a CMS edit to
-- these cells. Unlike the earlier passes, Weeks 3-4 is live to a running cohort,
-- so confirm none of these three cells has been published through the admin CMS
-- before deploying; if one has, fold the live copy into the seed JSON first.
--
-- Learner progress is deliberately NOT reset. progress_reset_at is minted
-- inside the admin-content Edge Function, so a migration cannot fire the epoch
-- protocol anyway; a copy pass that does need a reset has to go through the
-- admin CMS publish dialog instead.
--
-- Idempotent: re-running writes identical values.

do $$
declare
  missing text[];
begin
  select array_agg(c) into missing
  from unnest(array['c1-w34-pod-kickoff', 'c1-w34-walk-the-workflow-general', 'c1-w34-scavenger-hunt']) as c
  where not exists (select 1 from public.modules m where m.cell_id = c);

  if missing is not null then
    raise notice 'weeks34_pod_activity_copy: % target cell(s) absent, their updates will affect 0 rows: %',
      array_length(missing, 1), array_to_string(missing, ', ');
  end if;
end $$;

-- c1-w34-pod-kickoff — Meeting 1: Intros → Walk the Workflow → Delegation List
-- retitled to name the meeting and its agenda; Activity 2 navigation instructions + Activity 3 rewrite into timeboxed, tiered steps
update public.modules set
  title = 'Meeting 1: Intros → Walk the Workflow → Delegation List',
  body_md = $md$Welcome to your Week 3–4 pod activities! Complete the pod activities across roughly 2 hours. We recommend two 1-hour meetings; here's a starting suggestion for dividing the activities:

- **Meeting 1:** Get to Know Your Pod (15–20 min) → Walk the Workflow (20 min) → AI Delegation List Brainstorm (20 min)
- **Meeting 2:** AI Practice Scavenger Hunt (60 min)

For the best learning experience, please complete the activities in order and aim to spend about the indicated time on each so that you can get through all of them. You can always go back and revisit earlier activities another time — or at the end, if you finish early.

## Activity 1: Get to Know Your Pod (15–20 min)

If not everyone in your pod knows each other, have each person give a 1-minute intro:

- Name, pronouns
- Role / project
- Tenure at Nava
- Either:
  - Something that excites you outside of work — generally (e.g., gardening) or specifically right now (e.g., "I grew so many tomatoes this year I'm currently working on a pasta sauce recipe")
  - Or a boring fact about you (e.g., "I always/never pair my socks"; "I only like bananas that have no brown spots"; "washing dishes is my least favorite chore")

Then have each person take 1 minute to describe their current level of experience with AI so far.

- There are no wrong answers here. Keep your pod a judgement-free zone, and remember to keep what's shared in pods private to your group (except for learning artifacts that might help others — share those only with the group's agreement).
- Ideas for what to share (you do not need to address all of these): what you've tried or not tried; what you want to try; what's worked or not worked for you; any specific goals you have for AI use.

## Activity 2: Walk the Workflow (20 min)

Choose one **Walk the Workflow** activity to complete as a group. Choose whether you'd like to complete a **delivery-** or **non-delivery-based** scenario and go to the relevant tab in the left navigation bar. Then follow your selected scenario and complete each decision point as a group. Come back to this section afterward to pick up with the next activity.

- Delivery scenario: *Walk the Workflow: Delivery Scenario*
- Non-delivery scenario: *Walk the Workflow: General Operations Scenario*

## Activity 3: AI Delegation List Brainstorm (20 min)

One way to set yourself up for success when using AI is to proactively reflect on the types of tasks within your workflows that make sense to delegate to an LLM — and which do not.

1. **5–7 minutes.** **Independently** brainstorm **3 tasks**, and sort each into one of the three categories: **Full pass to AI**, **AI-assisted**, or **Human Only**.
   - Reflect on *why* certain tasks fit into each tier, and be ready to discuss your reasoning.
   - You can choose tasks that you have already delegated before, or tasks that you think you could delegate or want to delegate.
2. **7–10 minutes.** Then discuss what you brainstormed **as a group**:
   - What tasks did everyone choose for each tier?
   - What reasonings did everyone use to inform their choices?
   - If your group lands on a task that everyone agrees to fully delegate to AI, do a quick gut check: would you be comfortable if a client or manager saw the AI's unreviewed output? If the answer is no, that task probably needs a human check.
   - If any delegation decisions were unclear, make a note and ask about them in your cohort Slack channel.
3. **3–5 minutes.** If it makes sense for your pod's interests, choose a shared goal (or goals) for the type of AI task(s) you want to try together. Are any of the tasks you identified to delegate reasonable to practice or work on together? At your next session you'll have semi-structured AI exploration time.
   - Did anyone list a task they'd like to delegate but haven't yet, or a task they want to improve how they delegate?
   - Feel free to use actual work examples and tackle something you're working on now. Bring any resources you'd need to your next meeting.$md$
where cell_id = 'c1-w34-pod-kickoff';

-- c1-w34-walk-the-workflow-general — Walk the Workflow: General Operations Scenario
-- Devon scenario: source descriptions and two feedback grammar fixes
update public.modules set
  lab_config_json = $json${
  "kind": "decision-scenario",
  "title": "Walk the Workflow: General operations scenario",
  "subtitle": "Delegate → Ground → Scope → Verify, one decision at a time.",
  "introMd": "Devon works on Nava's People Operations team. Nava just switched to a new benefits-enrollment platform, and the internal \"Benefits 101\" guide — the doc every employee gets pointed to during onboarding and open enrollment — still describes the old system. Devon owns the rewrite: the steps need to match the new platform exactly, the tone should stay friendly and plain, and it's due before open enrollment starts in two weeks. Devon uses Claude for small things but has never used it for a full document like this.\n\nWalk through Devon's task one decision at a time. At each checkpoint, discuss as a pod before choosing an answer.",
  "checkpoints": [
    {
      "id": "delegate",
      "phase": "delegate",
      "setupMd": "**Discuss:** How, if at all, could Devon most effectively delegate to AI here, and what reasoning supports that choice?\n\n- What details about the task help you decide?",
      "prompt": "Devon should:",
      "options": [
        {
          "text": "Hand the task fully to AI — it's an internal doc, not client work, so the stakes are low, and rewriting a guide is exactly what AI is good at.",
          "feedbackMd": "Internal doesn't mean low-stakes: every employee will follow this guide to make real benefits decisions, and wrong steps mean missed enrollments and a flood of help requests. Restructuring and rewriting are a great fit for AI — but a human needs to own the accuracy of every step. AI-assisted, with Devon owning the final content, is the better choice."
        },
        {
          "text": "Use AI to restructure and redraft the guide, but personally own the accuracy of every step and the final wording, because employees will follow this guide to make real benefits decisions.",
          "feedbackMd": "This is the most effective choice. Reorganizing an existing document and redrafting it in a consistent tone is exactly the production work AI accelerates — and because employees will act on these instructions, Devon keeps ownership of step-by-step accuracy and the final wording. AI takes the rote work; Devon keeps the judgment."
        },
        {
          "text": "Do the task entirely without AI — benefits information is too sensitive to bring AI anywhere near it.",
          "feedbackMd": "The instinct to be careful around benefits information is right — but the *guide itself* is instructions for using a platform, and rewriting it is rote production work Devon would review either way. Avoiding AI entirely just costs Devon days of drafting. AI-assisted, with Devon owning the final content, is the better choice."
        }
      ]
    },
    {
      "id": "ground",
      "phase": "ground",
      "multiSelect": true,
      "setupMd": "Devon decides to use Claude to restructure and redraft the guide. Now: what sources should go into the model? Devon has the following available:\n\n- The **new platform's official administrator guide** from the vendor — public product documentation that describes every enrollment step accurately.\n- **Last year's \"Benefits 101\" guide** — the internal doc being replaced. The structure and tone are right; the steps are outdated. It contains no personal information about any employee.\n- A **spreadsheet of employees' current enrollment selections** that the benefits team uses for reporting. It would show which plans people actually pick.\n- A **Slack thread where a teammate collected complaints** and confusion from employees about the old guide — useful pain points that the team hasn't addressed yet, mixed in with individual employees' names and personal situations.\n\n**Discuss:** What should Devon put into the AI model to ground its work?\n\n- What details about the options help you decide?\n- Is there any additional information about any of the source options that would clarify whether they are safe or compliant to use with AI? *Hint: does Nava have a policy on this?*",
      "prompt": "Devon should use the following sources to ground the model — check all that apply. Only select sources that you are confident are appropriate; do not select any options that may be risky without more information.",
      "options": [
        {
          "text": "The vendor's official administrator guide",
          "feedbackMd": "A best choice. It's public product documentation, we know it's accurate, and it's exactly the source of truth the new steps need to match."
        },
        {
          "text": "Last year's \"Benefits 101\" guide",
          "feedbackMd": "A best choice. It's internal but contains no personal information, and it gives the model the structure and tone to preserve — reliable, relevant, and safe to use."
        },
        {
          "text": "The spreadsheet of employees' enrollment selections",
          "feedbackMd": "Do not put this in. It's employees' personal benefits data — and it isn't even needed for the task: the guide explains *how* to enroll, not *what* people picked. Sensitive personal data stays out of the model no matter how convenient it might seem."
        },
        {
          "text": "The Slack thread of collected complaints",
          "feedbackMd": "Risky as-is. The pain points are genuinely useful context, but giving Claude access to the thread mixes the content with individual employees' names and any personal situations they may have posted about. If Devon wants this context, the safer move is to first distill the *themes* — with every personal detail removed — and ground the model with that summary instead."
        }
      ]
    },
    {
      "id": "scope",
      "phase": "scope",
      "setupMd": "Devon decides to ground the model with the vendor's administrator guide and last year's \"Benefits 101\" doc. The vendor guide is long, and the old guide is about eight pages. Devon is eager to get a full draft quickly — but also worried about old-platform steps silently blending into the new-platform rewrite.\n\n**Discuss:** How should Devon write the prompt for this task?\n\n- What should go in the prompt that would help the AI produce a quality output?\n- What other prompting strategies might help?",
      "prompt": "Which prompt option below is best suited for Devon's ask?",
      "options": [
        {
          "text": "Use the long-running chat Devon already has for day-to-day HR questions — it's already familiar with how Devon likes things written — and ask it to rewrite the guide there.",
          "feedbackMd": "A long-running chat is a polluted context: Devon can't control what earlier material the model draws on, and stray context is exactly how old-platform steps sneak into a new-platform guide. Starting a fresh chat for a fresh task and chunking the work is the best option."
        },
        {
          "text": "Start a new chat and make one broad ask: \"Here's our old benefits guide and the new platform's documentation — rewrite the guide for the new platform.\" Then fix whatever's off during revision.",
          "feedbackMd": "One broad ask moves fast, but it blends the two sources in ways that are hard to audit — Devon would have to verify every sentence anyway, without a clear map of what changed. The speed usually comes back as extra revision work and a higher chance of uncaught errors. Using a new chat and chunking the work is the best option."
        },
        {
          "text": "Start a new chat and chunk the work: first ask for a list of every enrollment step that changed between the old guide and the new platform's documentation, quoting the vendor doc for each; then have it redraft the guide one section at a time, keeping last year's tone.",
          "feedbackMd": "This is the best option. The changed-steps list gives Devon a verification checklist *before* any drafting happens, and section-by-section drafting keeps each ask small enough to check along the way — control and efficiency at the same time."
        }
      ]
    },
    {
      "id": "verify",
      "phase": "verify",
      "setupMd": "The redraft is done, and it reads beautifully — friendly, clear, and organized. Devon's manager will give it a quick look before it goes into the onboarding folder, and the benefits team will hear about it soon enough if something's wrong. Open enrollment starts soon, and Devon is tempted to call it done.\n\n**Discuss:** How much does Devon need to verify the guide before handing it off?\n\n- What factors should inform this decision?",
      "prompt": "Which verification approach makes the most sense for Devon?",
      "options": [
        {
          "text": "Add a note that the guide was drafted with AI assistance, so readers know to double-check anything that looks off.",
          "feedbackMd": "A disclaimer isn't verification — it quietly shifts the checking onto every employee who reads the guide, and most will (reasonably) just follow the steps. Devon owns the accuracy of the deliverable. While a general disclaimer about AI use is a good practice to employ, in terms of verification, walking through the new guide step by step is the right approach."
        },
        {
          "text": "Read it through once for tone and obvious mistakes — Devon's manager is reviewing it next, so deep checking would be duplicated effort.",
          "feedbackMd": "A manager's quick look is not a step-by-step accuracy check, and Devon shouldn't pass the responsibility for finding AI errors downstream. A read-through for tone won't catch a wrong menu name or a missed deadline date — the errors that actually matter here. Walking through the new guide step by step is the right approach."
        },
        {
          "text": "Walk through the new guide step by step against the live platform (or the vendor documentation), confirming each instruction actually works, and flag anything that can't be confirmed before handing it off.",
          "feedbackMd": "This is the right approach. Instructions get verified by *doing* them: Devon clicks through the real enrollment flow with the guide in hand, confirms every step and figure against the vendor documentation, and flags anything unconfirmable rather than guessing."
        },
        {
          "text": "Verify every step — and if any step turns out wrong, discard the AI draft and rewrite the guide from scratch by hand, to be safe.",
          "feedbackMd": "Verify every step, yes — but one wrong step doesn't poison the document. Fix what's wrong, re-check the fix, and keep going. Scrapping working material after any single error trades away all the efficiency without adding safety. Walking through the new guide step by step, and fixing any errors as you go, is the right approach."
        }
      ]
    }
  ],
  "closingMd": "Even in internal-facing work, some AI errors are worth more than a quiet fix. Before you move on, reflect:\n\n- What kinds of errors in an internal document like this would you flag to others rather than silently correct? Why?\n\nYou'll learn more about how and when to escalate AI errors at your next live session."
}$json$::jsonb
where cell_id = 'c1-w34-walk-the-workflow-general';

-- c1-w34-scavenger-hunt — Meeting 2: AI Practice Scavenger Hunt
-- Cowork hint, connector/model support-doc links, closing apply-it paragraph, punctuation fixes
update public.modules set
  body_md = $md$We recommend completing this activity during your second pod meeting of Weeks 3-4. Plan to spend about 1 hour on these tasks.

Choose **at least 3–4** of the tasks/exercises from the list below to try with your pod. You can work on each of them together, or choose to work on them in smaller groups or independently first before debriefing. You do not need to complete them in order. Feel free to try tasks that align with real work needs — or just try items for fun. Think back to any goals you set as a group at the end of your first meeting. The goal is to build familiarity with self-led experimentation.

Choose the exercises that are most interesting to you, your pod, and your work — but **pick one from the Judgement / Workflow Reps category to start**. Note any challenges or questions and post them in your cohort Slack channel.

**Feeling stuck for material?** Pick any public article about AI (or any public document related to your work) and use it as your source material: prompt the AI to summarize, compare, or write something based on the content — or manipulate it in some way.

## Judgement / Workflow Reps

1. **Grounding-for-improvement A/B test.** Run one task or prompt cold, then again with the real source pasted in. Compare, then verify one claim in the grounded version. (This is the Week 2 activity, now open to whatever prompts you'd like to try.)
2. **Break your own scope.** Take a broad task and create a multi-part request with multiple prompts for the LLM. For example, instead of prompting the AI to draft or code an entire deliverable at once, identify several steps or chunks to run with separate prompts.
3. **Search for a hallucination.** Ask the LLM about something very niche and specific to your domain expertise, where you know the truth. See if you can catch the model being confidently wrong. If you succeed — what made the incorrect response seem credible?
4. **Verify a real output.** Ask AI to draft something related to an actual work need (or pull up something you previously drafted with AI) and do a stakes-appropriate verification pass — or part of one, depending on the size of your draft. Did you catch any errors? What types of details did you need to verify?
5. **Write a reusable prompt.** Turn a task you often do into a saved prompt template with clear instructions — e.g., a prompt template for summarizing documents, reviewing code, or helping you brainstorm.
6. **Test different Claude profile instructions.** Try changing your Claude instructions in various ways and see how responses change. For example, try different tones or styles, or set different restrictions on length or format.

## Tool Exploration

1. **Turn on and test multiple Claude [connectors](https://support.claude.com/en/articles/11176164-use-connectors-to-extend-claude-s-capabilities).** Notice the different permissions options each one asks for.
2. **Try a skill from the [skill library](https://hub.navapbc.com).** Browse the skill library in Claude, pick one that looks useful for your work, and run it on a real task. How did it work?
3. **Use Cowork to design a basic skill.** Start from a task you repeat often, and work with Cowork to turn it into a simple reusable skill. (Hint: start by prompting Claude with, "Guide me in creating a new skill.")
4. **Try using Notebook to create several different artifacts** from the same material.
5. **Compare multiple [different models](https://support.claude.com/en/articles/8664678-change-the-model-effort-and-thinking-settings).** For example, run the same prompt in Claude using Haiku, then Sonnet, then Opus. (You could also try using the same prompt in Claude and in Gemini.) What do you notice?
6. **For engineers — or anyone with coding experience and access: try Claude Code.** How did it work?

Before you wrap up, take a moment to think about how you can apply one of today's exercises to your own work. Is there a task on your plate right now where one of these tools or approaches would help? Try putting it into practice where relevant!$md$
where cell_id = 'c1-w34-scavenger-hunt';

do $$
declare
  updated int;
begin
  select count(*) into updated
  from public.modules
  where cell_id = any (array['c1-w34-pod-kickoff', 'c1-w34-walk-the-workflow-general', 'c1-w34-scavenger-hunt']);
  raise notice 'weeks34_pod_activity_copy: reconciled % of 3 reviewed cell(s).', updated;
end $$;
